name: build

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build utilities
        run: sudo apt-get install -y zip
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Build server
        run: |
          pushd src/RssReader
          dotnet publish -c Release
          popd
          pushd src/RssReader/bin/Release/net6.0/publish
          zip -r server.zip *
          popd
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_id }}.${{ github.run_number }}
          release_name: Release v${{ github.run_id }}.${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload server assets
        id: upload-server-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: src/RssReader/bin/Release/net6.0/publish/server.zip
          asset_name: server.zip
          asset_content_type: application/zip
